/* DO NOT EDIT THIS FILE - it is machine generated */

#include <jni.h>
#include <string>

#pragma once

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_example_pythontest_PythonThread
 * Method:    initPython
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_pythontest_PythonThread_initPython
  (JNIEnv *, jobject, jstring aPath, jstring aSetupDirectory);

/*
 * Class:     com_example_pythontest_PythonThread
 * Method:    cleanupPython
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_pythontest_PythonThread_cleanupPython
  (JNIEnv *, jobject);

/*
 * Class:     com_example_pythontest_PythonThread
 * Method:    runPython
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_pythontest_PythonThread_runPython
  (JNIEnv *, jobject, jstring filename);



#ifdef __cplusplus
}
#endif

